use crate::bspline::basis::BsplineBasis;
use crate::index::dimensioned::{DimShape, Strides};
use crate::index::multi_index::MultiIndex;
use itertools::Itertools;
use nalgebra::{DVector, RealField};
use std::iter::zip;
use std::marker::PhantomData;

/// A [`BsplineBasis`] generated by tensor products of (univariate) bases.
/// Given a family `{B[i]}ᵢ` of [`D`] bases with `B[i] = {b₁,...,bₙ}`,
/// the tensor product basis functions are defined as
/// ```text
/// bᵢ: X×...×X ⟶ ℝ   x ↦ bᵢ[1](x[1]) ... bᵢ[d](x[d])
/// ```
#[derive(Debug, Clone, Copy)]
pub struct MultiProd<T: RealField, B: BsplineBasis<T, T, 1>, const D: usize> {
    /// The bases for each parametric direction.
    pub bases: [B; D],

    _phantom_data: PhantomData<T>,
}

impl<T: RealField, B: BsplineBasis<T, T, 1>, const D: usize> MultiProd<T, B, D>
    where B::NonzeroIndices: Clone
{
    /// Constructs a new [`MultiProd`] from the given array `bases` of `D` univariate bases.
    pub fn new(bases: [B; D]) -> Self {
        MultiProd { bases, _phantom_data: Default::default() }
    }

    /// Returns the number of basis functions per parametric direction as a [`DimShape`].
    pub fn num_basis(&self) -> DimShape<D> {
        let arr = self.bases.iter()
            .map(|base| base.len())
            .collect_array();
        DimShape(arr.unwrap())
    }

    /// Returns the [`Strides`] for the basis functions.
    pub fn strides(&self) -> Strides<D> {
        Strides::from(self.num_basis())
    }

    /// Evaluates the nonzero basis functions using a tensor product algorithm.
    fn eval_tensor_prod(&self, x: [T; D]) -> (DVector<T>, impl Iterator<Item = usize>) {
        let (b, idx): (Vec<_>, Vec<_>) = zip(&self.bases, x)
            .map(|(space, xi)| space.eval_nonzero(xi))
            .unzip();

        let b = b.into_iter()
            .reduce(|acc, bi| acc.kronecker(&bi))
            .expect("Dimension D must be greater than 0!");

        let strides = self.strides();
        let idx = idx.into_iter()
            .multi_cartesian_product()
            .map(|i| TryInto::<[usize; D]>::try_into(i).unwrap())
            .map(move |i| i.into_lin(&strides));

        (b, idx)
    }
}

impl <T: RealField, B: BsplineBasis<T, T, 1>> BsplineBasis<T, T, 1> for MultiProd<T, B, 1>
    where B::NonzeroIndices: Clone
{
    type NonzeroIndices = impl Iterator<Item = usize>;

    fn len(&self) -> usize {
        self.num_basis().len()
    }

    fn eval_nonzero(&self, x: T) -> (DVector<T>, Self::NonzeroIndices) {
        self.eval_tensor_prod([x])
    }
}

impl <T: RealField, B: BsplineBasis<T, T, 1>> BsplineBasis<T, (T, T), 1> for MultiProd<T, B, 2>
    where B::NonzeroIndices: Clone
{
    type NonzeroIndices = impl Iterator<Item = usize>;

    fn len(&self) -> usize {
        self.num_basis().len()
    }

    fn eval_nonzero(&self, x: (T, T)) -> (DVector<T>, Self::NonzeroIndices) {
        self.eval_tensor_prod([x.0, x.1])
    }
}

impl <T: RealField, B: BsplineBasis<T, T, 1>, const D: usize> BsplineBasis<T, [T; D], 1> for MultiProd<T, B, D>
    where B::NonzeroIndices: Clone
{
    type NonzeroIndices = impl Iterator<Item = usize>;

    fn len(&self) -> usize {
        self.num_basis().len()
    }

    fn eval_nonzero(&self, x: [T; D]) -> (DVector<T>, Self::NonzeroIndices) {
        self.eval_tensor_prod(x)
    }
}

/// A [`BsplineBasis`] generated by the tensor product of two bases [`B1`] and [`B2`].
#[derive(Debug, Clone, Copy)]
pub struct Prod<T: RealField, X, B1: BsplineBasis<T, X, 1>, B2: BsplineBasis<T, X, 1>> {
    /// First basis.
    b1: B1,

    /// Second basis.
    b2: B2,

    _phantom_data: PhantomData<(T, X)>,
}

impl<T: RealField, X, B1: BsplineBasis<T, X, 1>, B2: BsplineBasis<T, X, 1>> Prod<T, X, B1, B2> {
    /// Constructs a new [`Prod`] from the bases `b1` and `b2`.
    pub fn new(b1: B1, b2: B2) -> Self {
        Prod { b1, b2, _phantom_data: Default::default() }
    }

    /// Returns the number of basis functions per parametric direction as a [`DimShape`].
    pub fn num_basis(&self) -> DimShape<2> {
        DimShape([self.b1.len(), self.b2.len()])
    }

    /// Returns the [`Strides`] for the basis functions.
    pub fn strides(&self) -> Strides<2> {
        Strides::from(self.num_basis())
    }
}

impl <T: RealField, X: Copy, B1: BsplineBasis<T, X, 1>, B2: BsplineBasis<T, X, 1>> BsplineBasis<T, [X; 2], 1> for Prod<T, X, B1, B2>
    where B2::NonzeroIndices: Clone
{

    type NonzeroIndices = impl Iterator<Item = usize>;

    fn len(&self) -> usize {
        self.num_basis().len()
    }

    fn eval_nonzero(&self, x: [X; 2]) -> (DVector<T>, Self::NonzeroIndices) {
        let (b1, idx1) = self.b1.eval_nonzero(x[0]);
        let (b2, idx2) = self.b2.eval_nonzero(x[1]);

        let b = b1.kronecker(&b2); // todo: check order b1*b2 or b2*b1

        let strides = self.strides();
        let idx = idx1.cartesian_product(idx2)
            .map(move |i| i.into_lin(&strides));

        (b, idx)
    }
}