use crate::basis::local::LocalBasis;
use crate::index::dimensioned::{DimShape, Strides};
use crate::index::multi_index::MultiIndex;
use itertools::Itertools;
use nalgebra::{Const, Dyn, Matrix, OMatrix, RealField, RowDVector};
use std::iter::zip;
use std::marker::PhantomData;

/// A multivariate basis generated by tensor products of (univariate) scalar bases.
/// Given a family `{B[i]}ᵢ` of [`D`] bases with `B[i] = {b₁,...,bₙ}`,
/// the tensor product basis functions are defined as
/// ```text
/// bᵢ: X×...×X ⟶ ℝ   x ↦ bᵢ[1](x[1]) ... bᵢ[d](x[d])
/// ```
#[derive(Debug, Clone, Copy)]
pub struct MultiProd<T: RealField, B: LocalBasis<T, T, 1>, const D: usize> {
    /// The bases for each parametric direction.
    pub bases: [B; D],

    _phantom_data: PhantomData<T>,
}

impl<T: RealField, B: LocalBasis<T, T, 1>, const D: usize> MultiProd<T, B, D>
    where B::LinIndices: Clone
{
    /// Constructs a new [`MultiProd`] from the given array `bases` of `D` univariate bases.
    pub fn new(bases: [B; D]) -> Self {
        MultiProd { bases, _phantom_data: Default::default() }
    }

    /// Returns the number of basis functions per parametric direction as a [`DimShape`].
    pub fn num_basis(&self) -> DimShape<D> {
        let arr = self.bases.iter()
            .map(|base| base.num_basis())
            .collect_array();
        DimShape(arr.unwrap())
    }

    /// Returns the [`Strides`] for the basis functions.
    pub fn strides(&self) -> Strides<D> {
        Strides::from(self.num_basis())
    }

    /// Returns an iterator over all global indices of the tensor product basis functions
    /// in lexicographical order.
    fn global_indices_multi_prod(&self) -> impl Iterator<Item = usize> {
        let strides = self.strides();
        self.bases.iter()
            .map(|b| b.global_indices())
            .multi_cartesian_product()
            .map(|i| TryInto::<[usize; D]>::try_into(i).unwrap())
            .map(move |i| i.into_lin(&strides))
    }

    /// Evaluates the tensor product basis at `x`
    /// by applying [`Matrix::kronecker`] to each univariate basis.
    fn eval_multi_prod(&self, x: [T; D]) -> RowDVector<T> {
        zip(&self.bases, x)
            .map(|(b, xi)| b.eval(xi))
            .reduce(|acc, bi| acc.kronecker(&bi))
            .expect("Dimension D must be greater than 0!")
    }
}

impl <T: RealField, B: LocalBasis<T, T, 1>, const D: usize> LocalBasis<T, [T; D], 1> for MultiProd<T, B, D>
    where B::LinIndices: Clone
{
    type LinIndices = impl Iterator<Item = usize>;

    fn num_basis(&self) -> usize {
        self.num_basis().len()
    }

    fn global_indices(&self) -> Self::LinIndices {
        self.global_indices_multi_prod()
    }

    fn eval(&self, x: [T; D]) -> OMatrix<T, Const<1>, Dyn> {
        self.eval_multi_prod(x)
    }
}