pub mod examples;
mod edge;
mod face;
mod mesh;
pub(crate) mod patch;
mod plot;
mod repeated_averaging;
mod catmull_clark;
pub(crate) mod basis;
mod surface;
mod iga;
mod pde_examples;
mod cg;
mod quad;
mod precompute;